### ISSUE TITLE
"first" example crashes (reads from null pointer after last line of main())

### ISSUE THREAD

**Issue by Boscop** [sciter-sdk/rust-sciter#22] opened 2018-01-23 15:32 UTC
I downloaded the Sciter SDK, copied the sciter.dll for win64 and generated the sciter.lib file from it. I cloned rust-sciter and ran the examples, all worked except [`first`](https://github.com/sciter-sdk/rust-sciter/blob/master/examples/first.rs) which crashed:

          Running `target\debug\examples\first.exe`
    calling SciterAPI x64
    getting abi version
    sciter abi version: 0
    sciter class name: H-SMILE-CHILD
    sciter version: 4.1.1.5703 [4, 1, 1, 5703]
    error: process didn't exit successfully: `target\debug\examples\first.exe` (exit code: 3221225477)

> Unhandled exception at 0x00007FFB36A93499 (sciter.dll) in first.exe: 0xC0000005: Access violation reading location 0x0000000000000000.

So it's reading from a null pointer for some reason, after the last line of main, weird.. Any idea how to fix this? (I'm on Win8.1 btw)

**Comment by pravic** [comment] 2018-01-23 16:29
> and generated the sciter.lib file from it.

Why would you need it?

**Comment by pravic** [comment] 2018-01-23 16:30
But yes, a problem exists. I'll look on it.

**Comment by pravic** [comment] 2018-01-23 16:59
It looks like a problem in Sciter at the moment.

The [4.0.8.5649](https://github.com/c-smile/sciter-sdk/tree/aa2c7a1f9128c1a846e6fd6c6ab4f4172c4ccea5) works fine.

**Comment by pravic** [comment] 2018-01-23 17:18
Thanks for pointing it out. Apparently 4.1 versions of Sciter were poisoned with this bug.

**Comment by Boscop** [comment] 2018-01-24 01:11
Thanks. Where can I subscribee to this bug in sciter?

Do you know where can I download the SDK for version 4.0.8.5649? :)

From the whole zip I only need to extract the .dll, right?

**Comment by pravic** [comment] 2018-01-24 04:25
Here https://sciter.com/forums/ or here https://github.com/c-smile/sciter-sdk

It [is fixed](https://sciter.com/forums/topic/wm_destroy-access-violation-on-4-1-x-x/#post-55185) already and new build of sciter sdk will be available in the next release.

I gave you a link to the 4.0.8, you need only dll from there. Or you can clone the whole repository and checkout the specified version.

Sciter uses its own script which is incompatible with JS. An idea to support JS via external engine was considered from time to time since people keep asking it, but it's just an idea still.

**Comment by pravic** [comment] 2018-01-25 04:48
The issue is fixed in Sciter 4.1.2:

> sciter version: 4.1.2.5717 [4, 1, 2, 5717]

**Closed by pravic** 2018-01-25 04:48 UTC
Labels: bug, os:win
